apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: news-app-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Khumozin/news-app-gitops.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: news-app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true